# Run configuration for elastic stack
version: '2.1'

services:

  elasticsearch:
    build:
      context: elasticsearch/
      args:
        ELASTIC_VESRSION: $ELASTIC_VERSION
    container_name: elasticsearch
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      ELASTIC_PASSWORD: changeme

    networks:
      - elastic-network

  logstash:
    build:
      context: logstash/
      args:
        ELASTIC_VESRSION: $ELASTIC_VERSION
    container_name: logstash
    volumes:
      - ./logstash/config:/usr/share/logstash/config:ro
    ports:
      - "5000:5000/tcp"
      - "12201:12201/udp"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elastic-network
    depends_on:
      - elasticsearch

  kibana:
    build:
      context: kibana/
      args:
        ELASTIC_VESRSION: $ELASTIC_VERSION
    container_name: kibana
    volumes:
      - ./kibana/config:/usr/share/kibana/config:ro
    ports:
      - "5601:5601"
    networks:
      - elastic-network
    depends_on:
      - elasticsearch

networks:
  elastic-network:
    driver: bridge
