version: '2'

services:
  logspout:
    build:
      context: extensions/logspout
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      ROUTE_URIS: logstash://logstash:5000
      LOGSTASH_TAGS: elastic-docker
    networks:
      - elastic-network
    depends_on:
      - logstash
    restart: on-failure
